using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace DevCloud.Infrastructure.Services;

public sealed record ReportMetric(string Label, string Value);

public sealed record ReportData(
    string ProjectName,
    string ClientName,
    DateTimeOffset StartDate,
    DateTimeOffset EndDate,
    IReadOnlyList<ReportMetric> Metrics,
    string Narrative);

/// <summary>Renders a professional project report PDF using QuestPDF (Community license).</summary>
public sealed class ReportPdfService
{
    static ReportPdfService() => QuestPDF.Settings.License = LicenseType.Community;

    public byte[] Generate(ReportData data)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(t => t.FontSize(11).FontColor("#1f2933"));

                page.Header().Column(col =>
                {
                    col.Item().Text("DevCloud").FontSize(22).Bold().FontColor("#caa24a");
                    col.Item().Text("Project Report").FontSize(13).FontColor("#52606d");
                    col.Item().PaddingTop(2).Text($"{data.ProjectName}  •  {data.ClientName}").FontSize(11).SemiBold();
                    col.Item().Text($"{data.StartDate:yyyy-MM-dd} → {data.EndDate:yyyy-MM-dd}").FontSize(9).FontColor("#7b8794");
                    col.Item().PaddingTop(8).LineHorizontal(1).LineColor("#e4e7eb");
                });

                page.Content().PaddingVertical(14).Column(col =>
                {
                    col.Spacing(14);

                    col.Item().Text("Key Metrics").FontSize(14).Bold().FontColor("#caa24a");
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(c =>
                        {
                            c.RelativeColumn();
                            c.RelativeColumn();
                        });

                        foreach (var metric in data.Metrics)
                        {
                            table.Cell().Border(0.5f).BorderColor("#e4e7eb").Padding(8).Text(metric.Label).SemiBold();
                            table.Cell().Border(0.5f).BorderColor("#e4e7eb").Padding(8).Text(metric.Value);
                        }
                    });

                    col.Item().PaddingTop(6).Text("Summary").FontSize(14).Bold().FontColor("#caa24a");
                    foreach (var paragraph in data.Narrative.Split('\n', StringSplitOptions.RemoveEmptyEntries))
                    {
                        col.Item().Text(paragraph.Trim()).LineHeight(1.4f);
                    }
                });

                page.Footer().AlignCenter().Text(t =>
                {
                    t.Span("Generated by DevCloud AI  •  ").FontSize(8).FontColor("#9aa5b1");
                    t.Span($"{DateTimeOffset.UtcNow:yyyy-MM-dd HH:mm} UTC").FontSize(8).FontColor("#9aa5b1");
                });
            });
        }).GeneratePdf();
    }
}
